name: AmulyzeRPG
main: com.gmail.jpk.stu.AmulyzeRPG.AmulyzeRPG
version: 0.1
commands:
  amchat:
    description: Toggles amulyze chat for player.
    usage: /amchat
    permission: AmulyzeRPG.amchat
    permission-message: You don't have permission. Contact an admin.
  setlvl:
    description: Sets player's lvl.
    usage: /setlvl <player>
    permission: AmulyzeRPG.setlvl
    permission-message: You don't have permission.
  getlvl:
    description: Gets player's lvl.
    usage: /getlvl <player>
    permission: AmulyzeRPG.getlvl
    permission-message: You don't have permission.