name: AmulyzeRPG
main: com.gmail.jpk.stu.AmulyzeRPG.AmulyzeRPG
version: 0.1
authors: [Kody104, TSHC, mcyee]

commands:
  amchat:
    description: Toggles amulyze chat for player.
    usage: /amchat
    permission: AmulyzeRPG.amchat
    permission-message: You don't have permission. Contact an admin.
  getlvl:
    description: Gets player's lvl.
    usage: /getlvl <player>
    permission: AmulyzeRPG.getlvl
    permission-message: You don't have permission.
  global:
    description: Allows the player to chat globally.
    usage: /global <message>
    permission: AmulyzeRPG.global
    permission-message: If you see this, you have probably been silenced.
  quitclass:
    description: Quits player's lvl.
    usage: /quitclass
    permission: AmulyzeRPG.quitclass
    permission-message: You don't have permission.
  quitrole:
    description: Quits player's role
    usage: /quitrole
    permission: AmulyzeRPG.quitrole
    permission-message: You don't have permission.
  setclass:
    description: Sets the player's classtype
    usage: /setclass <class>
    permission: AmulyzeRPG.setclass
    permission-message: You don't have permission.
  setlvl:
    description: Sets player's lvl.
    usage: /setlvl <player>
    permission: AmulyzeRPG.setlvl
    permission-message: You don't have permission.
  setrole:
    description: Sets the player's role
    usage: /setrole <role>
    permission: AmulyzeRPG.setrole
    permission-message: You don't have permission.
  roll:
    description: Rolls player's item
    usage: /roll
    permission: AmulyzeRPG.roll
    permission-message: You don't have permission.
  sethome:
    description: Sets the player's respawn point
    usage: /sethome
    permission: AmulyzeRPG.sethome
    permission-message: You don't have permission.
  memos:
    description: Allows the player to manage memos
    usage: /memo <add | clear | delete | pop> <number | message>
    permission: AmulyzeRPG.memo
    permission-message: You don't have permission.
    
permissions:
  AmulyzeRPG.*:
    description: Gives access to all AmulyzeRPG commands
    children:
      AmulyzeRPG.amchat: true
      AmulyzeRPG.getlvl: true
      AmulyzeRPG.global: true
      AmulyzeRPG.quitclass: true
      AmulyzeRPG.quitrole: true
      AmulyzeRPG.setclass: true
      AmulyzeRPG.setlvl: true
      AmulyzeRPG.setrole: true
      AmulyzeRPG.roll: true
      AmulyzeRPG.sethome: true
      AmulyzeRPG.memos: true
  AmulyzeRPG.amchat:
    description: Toggles amulyze chat for player.
    default: true
  AmulyzeRPG.getlvl:
    description: Gets player's lvl.
    default: true
  AmulyzeRPG.global:
    description: Allows the player to chat globally
    default: true
  AmulyzeRPG.quitclass:
    description: Quits player's class
    default: true
  AmulyzeRPG.quitrole:
    description: Quits player's role
    default: true
  AmulyzeRPG.setclass:
    description: Sets player's class
    default: true
  AmulyzeRPG.setlvl:
    description: Sets player's lvl.
    default: false
  AmulyzeRPG.setrole:
    description: Allows the player to set their role
    default: true
  AmulyzeRPG.roll:
    description: Rolls player's item
    default: true
  AmulyzeRPG.sethome:
    description: Sets the player's respawn point
    default: true
  AmulyzeRPG.memos:
    description: Allows players to use memos
    default: true